#ifndef CAMERAREMOTEDEFINITIONS_H
#define CAMERAREMOTEDEFINITIONS_H

enum _CONNECTIONSTATE{
    _CONNECTIONSTATE_ERROR,
    _CONNECTIONSTATE_DISCONNECTED,
    _CONNECTIONSTATE_CONNECTET,
    _CONNECTIONSTATE_CONNECTING,
    _CONNECTIONSTATE_WATING,
    _CONNECTIONSTATE_SSDP_ALIVE_RECEIVED,
    _CONNECTIONSTATE_SSDP_BYEBYE_RECEIVED,
    _CONNECTIONSTATE_CAMERA_DETECTED
};


#endif // CAMERAREMOTEDEFINITIONS_H
